version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: '$DB_USER'
      POSTGRES_DB: '$DB_NAME'
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    tty: true
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
