# Generated by Django 4.2.7 on 2024-03-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='code_name')),
                ('description', models.TextField(verbose_name='description')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('lifetime', models.PositiveSmallIntegerField(default=1, verbose_name='lifetime')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'referral code',
                'verbose_name_plural': 'referral',
                'ordering': ['-date_created'],
            },
        ),
    ]
