# Generated by Django 4.2.7 on 2024-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_code', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
