# Generated by Django 4.2.7 on 2024-03-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_code', '0002_alter_referralcode_user_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='code'),
        ),
    ]
